name: Deploy

on:
  release:
    types: [created]

jobs:
  test:
    name: pre-process to publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: check version
        run: |
          npx can-npm-publish --verbose

  publish:
    name: publish to npm

    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install, publish
        run: |
          npm ci
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy:
    name: post-process to publish

    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install, deploy document
        run: |
          npm ci
          npx typedoc --out ./docs --mode file --ignoreCompilerErrors --theme minimal
          npx gh-pages -d docs -u "${{ secrets.PUBLISH_GH_PAGES_USER }}"  -r "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        env:
          CI: true
