name: Pre-Merge

on: [pull_request, push]

jobs:
  test:
    name: pre-process to merge

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, lint, type-check, and test
      run: |
        npm ci
        npm run lint
        npx tsc --noEmit
        npm test
      env:
        CI: true
