name: Pre-Merge

on: push

jobs:
  test:
    name: pre-process to merge

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, lint, type-check, and test
      run: |
        npm ci
        npm run lint
        npx tsc --noEmit
      env:
        CI: true
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.0
      args: '--ci'
